### ISSUE TITLE
希望更改默认主题

### ISSUE THREAD

**Issue by ghost** [LittleFish-233/moegirl-UWP#1]
原来的主题看不清，在设置里调整到了自定义图片透明度75%，现在体验非常棒，请问能优化一下默认主题吗？现在看不清。

**Comment by LittleFish-233** [comment]
你好，非常感谢你的支持。
目前的背景图片使用的是毛玻璃特效，如果不喜欢可以在设置里面修改。我举得默认保持现在这样就可以。
再次感谢你的建议！

**Comment by ghost** [comment]
不，我的意思是看这里——


![image](https://user-images.githubusercontent.com/59795360/133780351-e3162604-5879-47ff-827c-56c3e453aaaa.png)
![image](https://user-images.githubusercontent.com/59795360/133779056-d33538b4-a448-4ec2-966d-d6dd426523ec.png)


明显看不清楚字


能稍微升高些背景的不透明度吗 或者干脆默认白色透明？


![image](https://user-images.githubusercontent.com/59795360/133780503-a3fbc8f8-bcab-424c-96e2-d39b10d39046.png)

**Comment by LittleFish-233** [comment]
> 不，我的意思是看这里——
> 
> ![image](https://user-images.githubusercontent.com/59795360/133780351-e3162604-5879-47ff-827c-56c3e453aaaa.png)
> ![image](https://user-images.githubusercontent.com/59795360/133779056-d33538b4-a448-4ec2-966d-d6dd426523ec.png)
> 
> 明显看不清楚字
> 
> 能稍微升高些背景的不透明度吗 或者干脆默认白色透明？
> 
> ![image](https://user-images.githubusercontent.com/59795360/133780503-a3fbc8f8-bcab-424c-96e2-d39b10d39046.png)

好的，我这几天修改一下

**Comment by LittleFish-233** [comment]
![QTE`CM6OF%_1MDPXKDILX4C](https://user-images.githubusercontent.com/53342258/133886198-5cc374bb-9725-4b45-a368-89221b8d79e7.png)
这是新的默认效果，感觉会不会更好一点？

**Comment by ghost** [comment]
唔，还不错，我觉得你还可以尝试把超链接的蓝色改淡一些，这是来自H萌娘(萌娘百科里站)的代码
```
a, a:visited {
    text-decoration: none!important;
    color: #3366cc;
}
a:hover {
  text-decoration: none!important;
  color: #2a4b8d;
}
a.new {
color: #BA0000!important;
}
```
还去掉了条目链接的下划线，加上应该会美观很多

也可以增大一下萌娘百科的显示大小 把正文和gallery变大点
```
body {
    font-size: 108%;
}
```
或者加一个改变字号的设置如何 字变大后看着舒服 背景影响就会小很多

**Comment by LittleFish-233** [comment]
目前版本代码十分混乱（想穿越回去给自己讲讲软件工程的基本原则orz）
我试着修改一下，等有空我会重构一版。
上一次版本更新还在审核，通过后我会提交这一版本。

**Comment by LittleFish-233** [comment]
目前版本代码十分混乱（想穿越回去给自己讲讲软件工程的基本原则orz）
我试着修改一下，等有空我会重构一版。
上一次版本更新还在审核，通过后我会提交这一版本。

**Comment by ghost** [comment]
辛苦啦
