### ISSUE TITLE
网易云音乐部件加载错误

### ISSUE THREAD

**Issue by ghost** [LittleFish-233/moegirl-UWP#6]
部件加载为
![image](https://user-images.githubusercontent.com/59795360/133870351-b5a2fe16-72fc-48dd-b2bc-31b1c1cbd306.png)
辛苦啦

**Comment by LittleFish-233** [comment]
> 部件加载为
> ![image](https://user-images.githubusercontent.com/59795360/133870351-b5a2fe16-72fc-48dd-b2bc-31b1c1cbd306.png)
> 辛苦啦

请问能发一下具体的页面链接吗？

**Comment by ghost** [comment]
缘之空
